// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for HomeScreen documents */
interface HomeDocumentData {
    /**
     * Slice Zone field in *HomeScreen*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: home.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<HomeDocumentDataSlicesSlice>;
}
/**
 * Slice for *HomeScreen → Slice Zone*
 *
 */
type HomeDocumentDataSlicesSlice = SectionSliceSlice | HeroSliceSlice | Section2Slice | FooterSectionSlice | DiscoverSectionSlice | GallerySlice | Section3Slice | Section4Slice;
/**
 * HomeScreen document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;
/** Content for Page documents */
interface PageDocumentData {
    /**
     * Title field in *Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * content field in *Page*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.content
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    content: prismicT.RichTextField;
    /**
     * link field in *Page*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: page.link
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link: prismicT.LinkField;
    /**
     * Slice Zone field in *Page*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: page.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<PageDocumentDataSlicesSlice>;
}
/**
 * Slice for *Page → Slice Zone*
 *
 */
type PageDocumentDataSlicesSlice = SectionSliceSlice | HeroSliceSlice;
/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;
export type AllDocumentTypes = HomeDocument | PageDocument;
/**
 * Primary content in DiscoverSection → Primary
 *
 */
interface DiscoverSectionSliceDefaultPrimary {
    /**
     * Title field in *DiscoverSection → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: discover_section.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
}
/**
 * Item in DiscoverSection → Items
 *
 */
export interface DiscoverSectionSliceDefaultItem {
    /**
     * icon field in *DiscoverSection → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: discover_section.items[].icon
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    icon: prismicT.ImageField<never>;
    /**
     * Title field in *DiscoverSection → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: discover_section.items[].title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.RichTextField;
    /**
     * Content field in *DiscoverSection → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: discover_section.items[].content
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    content: prismicT.RichTextField;
}
/**
 * Default variation for DiscoverSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: `DiscoverSection`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type DiscoverSectionSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<DiscoverSectionSliceDefaultPrimary>, Simplify<DiscoverSectionSliceDefaultItem>>;
/**
 * Slice variation for *DiscoverSection*
 *
 */
type DiscoverSectionSliceVariation = DiscoverSectionSliceDefault;
/**
 * DiscoverSection Shared Slice
 *
 * - **API ID**: `discover_section`
 * - **Description**: `DiscoverSection`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type DiscoverSectionSlice = prismicT.SharedSlice<"discover_section", DiscoverSectionSliceVariation>;
/**
 * Primary content in Footer → Primary
 *
 */
interface FooterSectionSliceDefaultPrimary {
    /**
     * Title field in *Footer → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: footer_section.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * item1 field in *Footer → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer_section.primary.item1
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    item1: prismicT.RichTextField;
    /**
     * link1 field in *Footer → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: footer_section.primary.itemlink1
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    itemlink1: prismicT.LinkField;
    /**
     * item2 field in *Footer → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer_section.primary.item2
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    item2: prismicT.KeyTextField;
    /**
     * link2 field in *Footer → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: footer_section.primary.link2
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link2: prismicT.LinkField;
    /**
     * item3 field in *Footer → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer_section.primary.item3
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    item3: prismicT.KeyTextField;
    /**
     * link3 field in *Footer → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: footer_section.primary.link3
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link3: prismicT.LinkField;
    /**
     * item4 field in *Footer → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer_section.primary.item4
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    item4: prismicT.KeyTextField;
    /**
     * link4 field in *Footer → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: footer_section.primary.link4
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link4: prismicT.LinkField;
    /**
     * Title2 field in *Footer → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer_section.primary.title2
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title2: prismicT.KeyTextField;
    /**
     * Title3 field in *Footer → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer_section.primary.title3
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title3: prismicT.KeyTextField;
    /**
     * Title1 field in *Footer → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer_section.primary.title1
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title1: prismicT.RichTextField;
    /**
     * Subtitle field in *Footer → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer_section.primary.subtitle
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    subtitle: prismicT.KeyTextField;
    /**
     * Content field in *Footer → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer_section.primary.content
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    content: prismicT.KeyTextField;
}
/**
 * Default variation for Footer Slice
 *
 * - **API ID**: `default`
 * - **Description**: `FooterSection`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FooterSectionSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<FooterSectionSliceDefaultPrimary>, never>;
/**
 * Slice variation for *Footer*
 *
 */
type FooterSectionSliceVariation = FooterSectionSliceDefault;
/**
 * Footer Shared Slice
 *
 * - **API ID**: `footer_section`
 * - **Description**: `FooterSection`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FooterSectionSlice = prismicT.SharedSlice<"footer_section", FooterSectionSliceVariation>;
/**
 * Primary content in Gallery → Primary
 *
 */
interface GallerySliceDefaultPrimary {
    /**
     * Title field in *Gallery → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: gallery.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Subtitle field in *Gallery → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: gallery.primary.subtitle
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    subtitle: prismicT.RichTextField;
}
/**
 * Item in Gallery → Items
 *
 */
export interface GallerySliceDefaultItem {
    /**
     * image field in *Gallery → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: gallery.items[].image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
    /**
     * title field in *Gallery → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: gallery.items[].title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.RichTextField;
    /**
     * content field in *Gallery → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: gallery.items[].content
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    content: prismicT.RichTextField;
    /**
     * link1 field in *Gallery → Items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: gallery.items[].link1
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link1: prismicT.LinkField;
    /**
     * link2 field in *Gallery → Items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: gallery.items[].link2
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link2: prismicT.LinkField;
}
/**
 * Default variation for Gallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Gallery`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type GallerySliceDefault = prismicT.SharedSliceVariation<"default", Simplify<GallerySliceDefaultPrimary>, Simplify<GallerySliceDefaultItem>>;
/**
 * Slice variation for *Gallery*
 *
 */
type GallerySliceVariation = GallerySliceDefault;
/**
 * Gallery Shared Slice
 *
 * - **API ID**: `gallery`
 * - **Description**: `Gallery`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type GallerySlice = prismicT.SharedSlice<"gallery", GallerySliceVariation>;
/**
 * Primary content in HeroSlice → Primary
 *
 */
interface HeroSliceSliceDefaultPrimary {
    /**
     * Caption1 field in *HeroSlice → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: hero_slice.primary.caption1
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    caption1: prismicT.TitleField;
    /**
     * Caption2 field in *HeroSlice → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: hero_slice.primary.caption2
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    caption2: prismicT.RichTextField;
    /**
     * Caption3 field in *HeroSlice → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: hero_slice.primary.caption3
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    caption3: prismicT.RichTextField;
    /**
     * content field in *HeroSlice → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: hero_slice.primary.content
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    content: prismicT.RichTextField;
}
/**
 * Default variation for HeroSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: `HeroSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroSliceSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<HeroSliceSliceDefaultPrimary>, never>;
/**
 * Slice variation for *HeroSlice*
 *
 */
type HeroSliceSliceVariation = HeroSliceSliceDefault;
/**
 * HeroSlice Shared Slice
 *
 * - **API ID**: `hero_slice`
 * - **Description**: `HeroSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroSliceSlice = prismicT.SharedSlice<"hero_slice", HeroSliceSliceVariation>;
/**
 * Primary content in Section1 → Primary
 *
 */
interface SectionSliceSliceDefaultPrimary {
    /**
     * Title field in *Section1 → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: section_slice.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Subtitle field in *Section1 → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: section_slice.primary.subtitle
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    subtitle: prismicT.RichTextField;
    /**
     * content field in *Section1 → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: section_slice.primary.content
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    content: prismicT.KeyTextField;
    /**
     * description field in *Section1 → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: section_slice.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Default variation for Section1 Slice
 *
 * - **API ID**: `default`
 * - **Description**: `SectionSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SectionSliceSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<SectionSliceSliceDefaultPrimary>, never>;
/**
 * Slice variation for *Section1*
 *
 */
type SectionSliceSliceVariation = SectionSliceSliceDefault;
/**
 * Section1 Shared Slice
 *
 * - **API ID**: `section_slice`
 * - **Description**: `SectionSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SectionSliceSlice = prismicT.SharedSlice<"section_slice", SectionSliceSliceVariation>;
/**
 * Item in Section2 → Items
 *
 */
export interface Section2SliceDefaultItem {
    /**
     * Title field in *Section2 → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: section2.items[].title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * description field in *Section2 → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: section2.items[].description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * image field in *Section2 → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: section2.items[].image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
    /**
     * link field in *Section2 → Items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: section2.items[].link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link: prismicT.LinkField;
}
/**
 * Default variation for Section2 Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Section2`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type Section2SliceDefault = prismicT.SharedSliceVariation<"default", Record<string, never>, Simplify<Section2SliceDefaultItem>>;
/**
 * Slice variation for *Section2*
 *
 */
type Section2SliceVariation = Section2SliceDefault;
/**
 * Section2 Shared Slice
 *
 * - **API ID**: `section2`
 * - **Description**: `Section2`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type Section2Slice = prismicT.SharedSlice<"section2", Section2SliceVariation>;
/**
 * Primary content in Section3 → Primary
 *
 */
interface Section3SliceDefaultPrimary {
    /**
     * Title field in *Section3 → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: section3.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Description field in *Section3 → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: section3.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Default variation for Section3 Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Section3`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type Section3SliceDefault = prismicT.SharedSliceVariation<"default", Simplify<Section3SliceDefaultPrimary>, never>;
/**
 * Slice variation for *Section3*
 *
 */
type Section3SliceVariation = Section3SliceDefault;
/**
 * Section3 Shared Slice
 *
 * - **API ID**: `section3`
 * - **Description**: `Section3`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type Section3Slice = prismicT.SharedSlice<"section3", Section3SliceVariation>;
/**
 * Primary content in Section4 → Primary
 *
 */
interface Section4SliceDefaultPrimary {
    /**
     * Title field in *Section4 → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: section4.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * image field in *Section4 → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: section4.primary.image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
}
/**
 * Default variation for Section4 Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Section4`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type Section4SliceDefault = prismicT.SharedSliceVariation<"default", Simplify<Section4SliceDefaultPrimary>, never>;
/**
 * Slice variation for *Section4*
 *
 */
type Section4SliceVariation = Section4SliceDefault;
/**
 * Section4 Shared Slice
 *
 * - **API ID**: `section4`
 * - **Description**: `Section4`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type Section4Slice = prismicT.SharedSlice<"section4", Section4SliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { HomeDocumentData, HomeDocumentDataSlicesSlice, HomeDocument, PageDocumentData, PageDocumentDataSlicesSlice, PageDocument, AllDocumentTypes, DiscoverSectionSliceDefaultPrimary, DiscoverSectionSliceDefaultItem, DiscoverSectionSliceDefault, DiscoverSectionSliceVariation, DiscoverSectionSlice, FooterSectionSliceDefaultPrimary, FooterSectionSliceDefault, FooterSectionSliceVariation, FooterSectionSlice, GallerySliceDefaultPrimary, GallerySliceDefaultItem, GallerySliceDefault, GallerySliceVariation, GallerySlice, HeroSliceSliceDefaultPrimary, HeroSliceSliceDefault, HeroSliceSliceVariation, HeroSliceSlice, SectionSliceSliceDefaultPrimary, SectionSliceSliceDefault, SectionSliceSliceVariation, SectionSliceSlice, Section2SliceDefaultItem, Section2SliceDefault, Section2SliceVariation, Section2Slice, Section3SliceDefaultPrimary, Section3SliceDefault, Section3SliceVariation, Section3Slice, Section4SliceDefaultPrimary, Section4SliceDefault, Section4SliceVariation, Section4Slice };
    }
}
