// Code generated by Slice Machine. DO NOT EDIT.

import Description from './Description';
import DiscoverSection from './DiscoverSection';
import Footer from './Footer';
import Gallery from './Gallery';
import GalleryRow from './GalleryRow';
import HeroSlice from './HeroSlice';
import HeroV2 from './HeroV2';
import Section1 from './Section1';
import Section2 from './Section2';
import Section3 from './Section3';
import Section4 from './Section4';
import Section5 from './Section5';
import Stackedgallery from './Stackedgallery';
import TeamGallery from './TeamGallery';

export {
	Description,
	DiscoverSection,
	Footer,
	Gallery,
	GalleryRow,
	HeroSlice,
	HeroV2,
	Section1,
	Section2,
	Section3,
	Section4,
	Section5,
	Stackedgallery,
	TeamGallery,
};

export const components = {
	description: Description,
	discover_section: DiscoverSection,
	footer_section: Footer,
	gallery: Gallery,
	gallery_row: GalleryRow,
	hero_slice: HeroSlice,
	hero_v2: HeroV2,
	section_slice: Section1,
	section2: Section2,
	section3: Section3,
	section4: Section4,
	section5: Section5,
	stackedgallery: Stackedgallery,
	team_gallery: TeamGallery,
};
