// Code generated by Slice Machine. DO NOT EDIT.

import HeroSlice from './HeroSlice';
import Section1 from './Section1';
import Section2 from './Section2';

export {
	HeroSlice,
	Section1,
	Section2,
};

export const components = {
	hero_slice: HeroSlice,
	section_slice: Section1,
	section2: Section2,
};
